### ISSUE TITLE
Not installable under Python 3

### ISSUE THREAD

**Issue by miohtama** [heikoheiko/pyethapp#5]
Something is pinning down gipc to old broken version 0.4.0 preventing the installation. Running `pip install gipc` can get a fresh 0.6.0 package.

```
pip install pyethapp

Collecting pyethapp
  Downloading pyethapp-1.2.1-py2.py3-none-any.whl (331kB)
    100% |████████████████████████████████| 337kB 1.9MB/s 
Requirement already satisfied (use --upgrade to upgrade): ipython>=3.0.0 in /Users/mikko/code/xxx/venv/lib/python3.5/site-packages (from pyethapp)
Collecting pexpect (from pyethapp)
  Downloading pexpect-4.0.1.tar.gz (143kB)
    100% |████████████████████████████████| 153kB 3.5MB/s 
Collecting wheel (from pyethapp)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in /Users/mikko/code/xxx/venv/lib/python3.5/site-packages (from pyethapp)
Requirement already satisfied (use --upgrade to upgrade): click in /Users/mikko/code/xxx/venv/lib/python3.5/site-packages (from pyethapp)
Collecting statistics (from pyethapp)
  Downloading statistics-1.0.3.5.tar.gz
Requirement already satisfied (use --upgrade to upgrade): decorator in /Users/mikko/code/xxx/venv/lib/python3.5/site-packages (from pyethapp)
Collecting gevent==1.1.0 (from pyethapp)
  Downloading gevent-1.1.0-cp35-cp35m-macosx_10_6_intel.whl (471kB)
    100% |████████████████████████████████| 481kB 1.4MB/s 
Collecting pbkdf2 (from pyethapp)
  Downloading pbkdf2-1.3.tar.gz
Collecting CodernityDB (from pyethapp)
  Downloading CodernityDB-0.5.0.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 4.5MB/s 
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Users/mikko/code/xxx/venv/lib/python3.5/site-packages (from pyethapp)
Collecting ethereum>=1.2.0 (from pyethapp)
  Downloading ethereum-1.2.0.tar.gz (112kB)
    100% |████████████████████████████████| 122kB 631kB/s 
Collecting lmdb (from pyethapp)
  Downloading lmdb-0.89.tar.gz (149kB)
    100% |████████████████████████████████| 153kB 2.8MB/s 
Collecting leveldb (from pyethapp)
  Downloading leveldb-0.193.tar.gz (224kB)
    100% |████████████████████████████████| 225kB 1.9MB/s 
Collecting rlp>=0.4.4 (from pyethapp)
  Downloading rlp-0.4.4-py2.py3-none-any.whl
Collecting gipc==0.4.0 (from pyethapp)
  Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6k/b150546j3yj_1_8823kgsfqc0000gn/T/pip-build-yqsfg_fh/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6k/b150546j3yj_1_8823kgsfqc0000gn/T/pip-build-yqsfg_fh/gipc/


pip install gipc

Collecting gipc
  Downloading gipc-0.6.0.zip
Collecting gevent>=1.1b1 (from gipc)
  Downloading gevent-1.1.1-cp35-cp35m-macosx_10_6_intel.whl (473kB)
    100% |████████████████████████████████| 481kB 1.5MB/s 
Collecting greenlet>=0.4.9 (from gevent>=1.1b1->gipc)
  Downloading greenlet-0.4.9.zip (78kB)
    100% |████████████████████████████████| 81kB 4.6MB/s 
Installing collected packages: greenlet, gevent, gipc
  Running setup.py install for greenlet ... done
  Running setup.py install for gipc ... done
Successfully installed gevent-1.1.1 gipc-0.6.0 greenlet-0.4.9
```

**Comment by miohtama** [comment]
Whoops wrong repo.
